// <auto-generated />
using System;
using LearnStack.Modules.Education.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LearnStack.Modules.Education.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EducationDbContext))]
    [Migration("20260914121240_create_education_schema")]
    partial class create_education_schema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LearnStack.Modules.Education.Domain.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("LevelBandKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("level_band_key");

                    b.Property<string>("LevelTaxonomyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("level_taxonomy_key");

                    b.Property<int?>("LevelTaxonomySchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("level_taxonomy_schema_version");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("SlugKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("slug_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("pk_courses");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ux_courses_tenant_id_id");

                    b.HasIndex("TenantId", "OrganizationId")
                        .HasDatabaseName("ix_courses_tenant_id_organization_id");

                    b.HasIndex("TenantId", "SlugKey")
                        .IsUnique()
                        .HasDatabaseName("ux_courses_tenant_id_slug_key")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("TenantId", "OrganizationId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_courses_tenant_id_organization_id_created_at_id")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("courses", null, t =>
                        {
                            t.HasCheckConstraint("ck_courses_level_reference", "(level_taxonomy_key IS NULL AND level_taxonomy_schema_version IS NULL AND level_band_key IS NULL)\nOR (level_taxonomy_key IS NOT NULL AND level_taxonomy_schema_version IS NOT NULL\n    AND level_taxonomy_schema_version > 0 AND level_band_key IS NOT NULL)");

                            t.HasCheckConstraint("ck_courses_slug_key_format", "slug_key ~ '^[a-z0-9]+(-[a-z0-9]+)*$' AND slug_key !~ '^[0-9a-f]{32}$' AND slug_key !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'");

                            t.HasCheckConstraint("ck_courses_status", "status IN ('draft', 'published')");
                        });
                });

            modelBuilder.Entity("LearnStack.Modules.Education.Domain.CourseTranslation", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<string>("Locale")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("locale");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("slug");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("CourseId", "Locale")
                        .HasName("pk_course_translations");

                    b.HasAlternateKey("TenantId", "Locale", "Slug")
                        .HasName("ux_course_translations_tenant_id_locale_slug");

                    b.HasIndex("TenantId", "CourseId")
                        .HasDatabaseName("ix_course_translations_tenant_id_course_id");

                    b.HasIndex("TenantId", "OrganizationId")
                        .HasDatabaseName("ix_course_translations_tenant_id_organization_id");

                    b.ToTable("course_translations", null, t =>
                        {
                            t.HasCheckConstraint("ck_course_translations_slug_format", "slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$' AND slug !~ '^[0-9a-f]{32}$' AND slug !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'");
                        });
                });

            modelBuilder.Entity("LearnStack.Modules.Education.Domain.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentTypeKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type_key");

                    b.Property<int>("ContentTypeSchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("content_type_schema_version");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("pk_lessons");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ux_lessons_tenant_id_id");

                    b.HasIndex("TenantId", "CourseId")
                        .HasDatabaseName("ix_lessons_tenant_id_course_id");

                    b.HasIndex("TenantId", "OrganizationId")
                        .HasDatabaseName("ix_lessons_tenant_id_organization_id");

                    b.HasIndex("TenantId", "CourseId", "Sort", "Id")
                        .HasDatabaseName("ix_lessons_tenant_id_course_id_sort_id")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("lessons", null, t =>
                        {
                            t.HasCheckConstraint("ck_lessons_content_type_schema_version", "content_type_schema_version > 0");

                            t.HasCheckConstraint("ck_lessons_sort", "sort >= 0");

                            t.HasCheckConstraint("ck_lessons_status", "status IN ('draft', 'published')");
                        });
                });

            modelBuilder.Entity("LearnStack.Modules.Education.Domain.LessonTranslation", b =>
                {
                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<string>("Locale")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("locale");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("body");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("slug");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("LessonId", "Locale")
                        .HasName("pk_lesson_translations");

                    b.HasAlternateKey("TenantId", "Locale", "Slug")
                        .HasName("ux_lesson_translations_tenant_id_locale_slug");

                    b.HasIndex("TenantId", "LessonId")
                        .HasDatabaseName("ix_lesson_translations_tenant_id_lesson_id");

                    b.HasIndex("TenantId", "OrganizationId")
                        .HasDatabaseName("ix_lesson_translations_tenant_id_organization_id");

                    b.ToTable("lesson_translations", null, t =>
                        {
                            t.HasCheckConstraint("ck_lesson_translations_body_object", "jsonb_typeof(body) = 'object'");

                            t.HasCheckConstraint("ck_lesson_translations_slug_format", "slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$' AND slug !~ '^[0-9a-f]{32}$' AND slug !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'");
                        });
                });

            modelBuilder.Entity("LearnStack.Modules.Education.Domain.CourseTranslation", b =>
                {
                    b.HasOne("LearnStack.Modules.Education.Domain.Course", null)
                        .WithMany("Translations")
                        .HasForeignKey("TenantId", "CourseId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_translations_course");
                });

            modelBuilder.Entity("LearnStack.Modules.Education.Domain.Lesson", b =>
                {
                    b.HasOne("LearnStack.Modules.Education.Domain.Course", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CourseId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lessons_course");
                });

            modelBuilder.Entity("LearnStack.Modules.Education.Domain.LessonTranslation", b =>
                {
                    b.HasOne("LearnStack.Modules.Education.Domain.Lesson", null)
                        .WithMany("Translations")
                        .HasForeignKey("TenantId", "LessonId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_translations_lesson");
                });

            modelBuilder.Entity("LearnStack.Modules.Education.Domain.Course", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("LearnStack.Modules.Education.Domain.Lesson", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
