<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>LearnStack.Modules.Education.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\LearnStack.SharedKernel\LearnStack.SharedKernel.csproj" />
    <ProjectReference Include="..\LearnStack.Modules.Education.Domain\LearnStack.Modules.Education.Domain.csproj" />
    <ProjectReference Include="..\LearnStack.Modules.Education.Application.Contracts\LearnStack.Modules.Education.Application.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
  </ItemGroup>

</Project>
