// <auto-generated />
using System;
using System.Net;
using LearnStack.Modules.Audit.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LearnStack.Modules.Audit.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20260908120341_create_audit_schema")]
    partial class create_audit_schema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LearnStack.Modules.Audit.Domain.AuditConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("module");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("operation");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("pk_audit_config");

                    b.HasIndex("TenantId", "ModuleName", "Operation")
                        .IsUnique()
                        .HasDatabaseName("ux_audit_config_tenant_id_module_operation");

                    b.ToTable("audit_config", (string)null);
                });

            modelBuilder.Entity("LearnStack.Modules.Audit.Domain.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("ActorEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("actor_email");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("AfterState")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_state");

                    b.Property<string>("BeforeState")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_state");

                    b.Property<string>("Changes")
                        .HasColumnType("jsonb")
                        .HasColumnName("changes");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity_type");

                    b.Property<string>("ErrorKey")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("error_key");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("module");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("operation");

                    b.Property<string>("OperationClass")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operation_class");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operation_type");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id", "Timestamp")
                        .HasName("audit_log_pkey");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_log_correlation_id")
                        .HasFilter("correlation_id IS NOT NULL");

                    b.HasIndex("ActorUserId", "Timestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_log_actor_user_id_timestamp")
                        .HasFilter("actor_user_id IS NOT NULL");

                    b.HasIndex("TenantId", "Timestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_log_tenant_id_timestamp");

                    b.HasIndex("ModuleName", "Operation", "Timestamp")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_audit_log_module_operation_timestamp");

                    b.ToTable("audit_log", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_log_operation_class", "operation_class IN ('Must', 'Should', 'May')");

                            t.HasCheckConstraint("ck_audit_log_operation_type", "operation_type IN ('Create', 'Update', 'Delete', 'ReadSensitive', 'SecurityEvent', 'PlatformAdmin', 'Action')");

                            t.HasCheckConstraint("ck_audit_log_outcome", "outcome IN ('success', 'denied', 'failed', 'indeterminate')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
