// <auto-generated />
using System;
using LearnStack.Modules.Customization.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LearnStack.Modules.Customization.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CustomizationDbContext))]
    [Migration("20260906100809_create_customization_schema")]
    partial class create_customization_schema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LearnStack.Modules.Customization.Domain.CustomizationGeneration", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Generation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("generation");

                    b.HasKey("TenantId")
                        .HasName("pk_customization_generations");

                    b.ToTable("customization_generations", (string)null);
                });

            modelBuilder.Entity("LearnStack.Modules.Customization.Domain.TenantContentType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("display_name");

                    b.Property<string>("JsonSchema")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("json_schema");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("RendererKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("renderer_key");

                    b.Property<int>("SchemaRevision")
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("schema_revision");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("pk_tenant_content_types");

                    b.HasAlternateKey("TenantId", "Key", "SchemaVersion")
                        .HasName("ux_tenant_content_types_tenant_id_key_schema_version");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_tenant_content_types_tenant_id_key_active")
                        .HasFilter("status = 'Active' AND deleted_at IS NULL");

                    b.ToTable("tenant_content_types", (string)null);
                });

            modelBuilder.Entity("LearnStack.Modules.Customization.Domain.TenantLevelTaxonomy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("display_name");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<int>("SchemaRevision")
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("schema_revision");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("pk_tenant_level_taxonomies");

                    b.HasAlternateKey("TenantId", "Key", "SchemaVersion")
                        .HasName("ux_tenant_level_taxonomies_tenant_id_key_schema_version");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_tenant_level_taxonomies_tenant_id_key_active")
                        .HasFilter("status = 'Active' AND deleted_at IS NULL");

                    b.ToTable("tenant_level_taxonomies", (string)null);
                });

            modelBuilder.Entity("LearnStack.Modules.Customization.Domain.TenantLevelTaxonomyItem", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TaxonomyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("taxonomy_key");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("display_name");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<short>("Sort")
                        .HasColumnType("smallint")
                        .HasColumnName("sort");

                    b.HasKey("TenantId", "TaxonomyKey", "SchemaVersion", "Key")
                        .HasName("pk_tenant_level_taxonomy_items");

                    b.HasIndex("TenantId", "TaxonomyKey", "SchemaVersion", "Sort")
                        .IsUnique()
                        .HasDatabaseName("ux_tenant_level_taxonomy_items_taxonomy_sort");

                    b.ToTable("tenant_level_taxonomy_items", (string)null);
                });

            modelBuilder.Entity("LearnStack.Modules.Customization.Domain.TenantLevelTaxonomyItem", b =>
                {
                    b.HasOne("LearnStack.Modules.Customization.Domain.TenantLevelTaxonomy", null)
                        .WithMany("Items")
                        .HasForeignKey("TenantId", "TaxonomyKey", "SchemaVersion")
                        .HasPrincipalKey("TenantId", "Key", "SchemaVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_level_taxonomy_items_taxonomy");
                });

            modelBuilder.Entity("LearnStack.Modules.Customization.Domain.TenantLevelTaxonomy", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
