<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>LearnStack.Modules.Content.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\LearnStack.SharedKernel\LearnStack.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\..\analyzers\LearnStack.Analyzers\LearnStack.Analyzers.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
